version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: npm run test:react:headless
workflows:
  build:
    jobs:
      - cypress/run
      - node/test:
          version: 12.16.3
  test:
    jobs:
      - test
