version: 2.1
orbs:
  cypress: cypress-io/cypress@1 #https://github.com/cypress-io/circleci-orb
jobs:
  check_environment:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: git --version
      #- run: npm run test:react:headless
      #- run: npm install
workflows:
  build:
    jobs:
      - cypress/install:
          build: "npm install" # run a custom app build step
          name: Install
      - check_environment:
          name: Print environment tool versions
          requires:
            - Install
      - cypress/run:
          name: Run all tests for react components
          command: npm run test:react:headless
          requires:
            - Install
      # - test:
      #     name: Run all tests for react components
      #     requires:
      #       - Install
