version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  node: circleci/node@12.6.3
jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      #- run: npm install
      #- run: npm run test:react:headless
      - run: node --version
workflows:
  install_and_test:
    jobs:
      # first, run a single job to install dependencies and Cypress
      # and perform a few more small steps like linting
      - cypress/install:
          name: Install
      - test:
          name: Run all tests for react components
          requires:
            - Install
