version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
jobs:
  test:
    docker:
      - image: circleci/node:12.6.13-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test:react:headless
workflows:
  install_and_test:
    jobs:
      # first, run a single job to install dependencies and Cypress
      # and perform a few more small steps like linting
      - cypress/install:
          name: Install
      - test:
          name: Run all tests for react components
          requires:
            - Install
