version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration
jobs:
  test:
    executor: node/default
    steps:
      - checkout
workflows:
  install_and_test:
    jobs:
      - cypress/run
      - test:
          requires:
            - cypress/run
