version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - run: npm run cypress:open:react:headless
workflows:
  install_and_test:
    jobs:
      # first, run a single job to install dependencies and Cypress
      # and perform a few more small steps like linting
      - cypress/install:
          name: Install
      - test:
          name: Run all tests
          requires:
            - Install
