version: 2.1
orbs:
  cypress: cypress-io/cypress@1 #https://github.com/cypress-io/circleci-orb
jobs:
  check_environment:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: git --version
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run clean:install' # run a custom app build step
          name: Install
      - check_environment:
          name: Print environment tool versions
          requires:
            - Install
      - cypress/run:
          name: Run all tests for react components
          command: npm run test:react:headless
          requires:
            - Install
          post-steps:
            - store_artifacts:
                path: coverage
